#
# This config exists as a demonstration of generating an alert with particular
# labels and sending to an alertmanager.
#
# We add env:local-dev as an external_label to make clear what's going
# on in the alertmanager
#
# Just run `prometheus` without any arguments from this directory.
global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    env: phils-laptop

rule_files:
  - 'rules/*'

alerting:
  alertmanagers:
  # Here is an example configuration for sending to a specific alertmanager:
  # it is commented out by default to avoid annoying the support person
  - scheme: https
    static_configs:
    - targets:
      - 'alerts-1.monitoring-staging.gds-reliability.engineering'
      - 'alerts-2.monitoring-staging.gds-reliability.engineering'
      - 'alerts-3.monitoring-staging.gds-reliability.engineering'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
