resource_types:
- name: cf
  type: docker-image
  source:
    repository: concourse/cf-resource
    tag: "1.1"
- name: git
  type: docker-image
  source:
    repository: concourse/git-resource
    tag: "1.6"

resources:
  - name: task-image
    type: docker-image
    icon: layers
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: prometheus-task-image
  - name: prometheus-aws-configuration-beta
    type: git
    icon: git
    source:
      uri: https://github.com/alphagov/prometheus-aws-configuration-beta.git
      branch: ((prometheus-aws-configuration-beta-branch))
  # image building is expensive even when nothing has changed, hence dedicated resource
  - name: prometheus-aws-configuration-beta-images
    type: git
    icon: git
    source:
      uri: https://github.com/alphagov/prometheus-aws-configuration-beta.git
      branch: ((prometheus-aws-configuration-beta-branch))
      paths:
        - ci/images
  - name: cf-app-discovery
    type: git
    icon: git
    source:
      uri: https://github.com/alphagov/cf_app_discovery.git
      branch: master
  - name: re-secrets
    type: git
    icon: git
    source:
      private_key: |
        ((re-secrets-ssh-key))
      uri: git@github.com:alphagov/re-secrets.git
      branch: master
      paths:
        - observe
  - name: service-broker-ireland-staging
    type: cf
    icon: anvil
    source:
      api: https://api.cloud.service.gov.uk
      username: ((cf_user))
      password: ((cf_password))
      organization: gds-tech-ops
      space: prometheus-staging
  - name: service-broker-ireland-production
    type: cf
    icon: anvil
    source:
      api: https://api.cloud.service.gov.uk
      username: ((cf_user))
      password: ((cf_password))
      organization: gds-tech-ops
      space: prometheus-production
  - name: service-broker-london-production
    type: cf
    icon: anvil
    source:
      api: https://api.london.cloud.service.gov.uk
      username: ((cf_london_user))
      password: ((cf_london_password))
      organization: gds-tech-ops
      space: prometheus-production

jobs:

  - name: configure-pipeline
    serial: true
    plan:
    - get: prometheus-aws-configuration-beta
      trigger: true
    - set_pipeline: self
      file: prometheus-aws-configuration-beta/ci/deploy.yml
      vars:
        prometheus-aws-configuration-beta-branch: ((prometheus-aws-configuration-beta-branch))

  - name: build-task-image
    serial: true
    plan:
    - get: prometheus-aws-configuration-beta-images
      trigger: true
    - put: task-image
      params: {build: prometheus-aws-configuration-beta-images/ci/images/task}
      get_params: {skip_download: true}

  - name: deploy-common-staging
    serial: true
    plan:
      - in_parallel:
        - get: prometheus-aws-configuration-beta
          passed: [configure-pipeline]
          trigger: true
        - get: task-image
          passed: [build-task-image]
          trigger: true
        - get: re-secrets
          trigger: true
      - task: apply-infra-networking-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        params:
          PROJECT: infra-networking-staging
          DEPLOYER_ARN: arn:aws:iam::027317422673:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))
      - task: apply-infra-security-groups-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        params:
          PROJECT: infra-security-groups-staging
          DEPLOYER_ARN: arn:aws:iam::027317422673:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))
      - task: apply-app-ecs-elbs-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        params:
          PROJECT: app-ecs-albs-staging
          DEPLOYER_ARN: arn:aws:iam::027317422673:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))

  - name: deploy-common-production
    serial: true
    plan:
      - in_parallel:
        - get: prometheus-aws-configuration-beta
          passed: [deploy-prometheus-staging, deploy-alertmanager-staging]
          trigger: true
        - get: task-image
          passed: [deploy-prometheus-staging, deploy-alertmanager-staging]
          trigger: true
        - get: re-secrets
          passed: [deploy-prometheus-staging, deploy-alertmanager-staging]
          trigger: true
      - task: apply-infra-networking-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        params:
          PROJECT: infra-networking-production
          DEPLOYER_ARN: arn:aws:iam::455214962221:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))
      - task: apply-infra-security-groups-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        params:
          PROJECT: infra-security-groups-production
          DEPLOYER_ARN: arn:aws:iam::455214962221:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))
      - task: apply-app-ecs-elbs-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        params:
          PROJECT: app-ecs-albs-production
          DEPLOYER_ARN: arn:aws:iam::455214962221:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))

  - name: deploy-prometheus-staging
    serial: true
    plan:
      - in_parallel:
        - get: prometheus-aws-configuration-beta
          passed: [deploy-common-staging]
          trigger: true
        - get: task-image
          passed: [deploy-common-staging]
          trigger: true
        - get: re-secrets
          passed: [deploy-common-staging]
          trigger: true
      - task: apply-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        output_mapping: {outputs: terraform-outputs}
        params:
          PROJECT: prom-ec2/paas-staging
          DEPLOYER_ARN: arn:aws:iam::027317422673:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))
      - task: generate-prometheus-test-jq
        image: task-image
        file: prometheus-aws-configuration-beta/ci/tasks/generate-prometheus-test-jq.yml
        input_mapping: {input: terraform-outputs}
        output_mapping: {output: prometheus-test-jq}
      - in_parallel:
        - do:
          - task: conf-test-prom-1
            attempts: 8
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            input_mapping: {response-jq-test: prometheus-test-jq}
            params:
              URL: https://prom-1.monitoring-staging.gds-reliability.engineering/last-config
          - task: smoke-test-prom-1
            attempts: 4
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            params:
              URL: https://prom-1.monitoring-staging.gds-reliability.engineering/-/ready
        - do:
          - task: conf-test-prom-2
            attempts: 8
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            input_mapping: {response-jq-test: prometheus-test-jq}
            params:
              URL: https://prom-2.monitoring-staging.gds-reliability.engineering/last-config
          - task: smoke-test-prom-2
            attempts: 4
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            params:
              URL: https://prom-2.monitoring-staging.gds-reliability.engineering/-/ready
        - do:
          - task: conf-test-prom-3
            attempts: 8
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            input_mapping: {response-jq-test: prometheus-test-jq}
            params:
              URL: https://prom-3.monitoring-staging.gds-reliability.engineering/last-config
          - task: smoke-test-prom-3
            attempts: 4
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            params:
              URL: https://prom-3.monitoring-staging.gds-reliability.engineering/-/ready

  - name: deploy-prometheus-production
    serial: true
    plan:
      - in_parallel:
        - get: prometheus-aws-configuration-beta
          passed: [deploy-common-production]
          trigger: true
        - get: task-image
          passed: [deploy-common-production]
          trigger: true
        - get: re-secrets
          passed: [deploy-common-production]
          trigger: true
      - task: apply-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        output_mapping: {outputs: terraform-outputs}
        params:
          PROJECT: prom-ec2/paas-production
          DEPLOYER_ARN: arn:aws:iam::455214962221:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))
      - task: generate-prometheus-test-jq
        image: task-image
        file: prometheus-aws-configuration-beta/ci/tasks/generate-prometheus-test-jq.yml
        input_mapping: {input: terraform-outputs}
        output_mapping: {output: prometheus-test-jq}
      - in_parallel:
        - do:
          - task: conf-test-prom-1
            attempts: 8
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            input_mapping: {response-jq-test: prometheus-test-jq}
            params:
              URL: https://prom-1.monitoring.gds-reliability.engineering/last-config
          - task: smoke-test-prom-1
            attempts: 4
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            params:
              URL: https://prom-1.monitoring.gds-reliability.engineering/-/ready
        - do:
          - task: conf-test-prom-2
            attempts: 8
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            input_mapping: {response-jq-test: prometheus-test-jq}
            params:
              URL: https://prom-2.monitoring.gds-reliability.engineering/last-config
          - task: smoke-test-prom-2
            attempts: 4
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            params:
              URL: https://prom-2.monitoring.gds-reliability.engineering/-/ready
        - do:
          - task: conf-test-prom-3
            attempts: 8
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            input_mapping: {response-jq-test: prometheus-test-jq}
            params:
              URL: https://prom-3.monitoring.gds-reliability.engineering/last-config
          - task: smoke-test-prom-3
            attempts: 4
            timeout: 2m
            file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
            params:
              URL: https://prom-3.monitoring.gds-reliability.engineering/-/ready

  - name: deploy-alertmanager-staging
    serial: true
    plan:
      - in_parallel:
        - get: prometheus-aws-configuration-beta
          passed: [deploy-common-staging]
          trigger: true
        - get: task-image
          passed: [deploy-common-staging]
          trigger: true
        - get: re-secrets
          passed: [deploy-common-staging]
          trigger: true
      - task: apply-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        params:
          PROJECT: alertmanager-staging
          DEPLOYER_ARN: arn:aws:iam::027317422673:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))
      - in_parallel:
        - task: smoke-test-alertmanager
          attempts: 4
          timeout: 2m
          file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
          params:
            URL: https://alerts.monitoring-staging.gds-reliability.engineering/-/healthy
        - task: smoke-test-alertmanager-eu-west-1a
          attempts: 4
          timeout: 2m
          file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
          params:
            URL: https://alerts-eu-west-1a.monitoring-staging.gds-reliability.engineering/-/healthy
        - task: smoke-test-alertmanager-eu-west-1b
          attempts: 4
          timeout: 2m
          file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
          params:
            URL: https://alerts-eu-west-1b.monitoring-staging.gds-reliability.engineering/-/healthy
        - task: smoke-test-alertmanager-eu-west-1c
          attempts: 4
          timeout: 2m
          file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
          params:
            URL: https://alerts-eu-west-1c.monitoring-staging.gds-reliability.engineering/-/healthy

  - name: deploy-alertmanager-production
    serial: true
    plan:
      - in_parallel:
        - get: prometheus-aws-configuration-beta
          passed: [deploy-common-production]
          trigger: true
        - get: task-image
          passed: [deploy-common-production]
          trigger: true
        - get: re-secrets
          passed: [deploy-common-production]
          trigger: true
      - task: apply-terraform
        image: task-image
        timeout: 15m
        file: prometheus-aws-configuration-beta/ci/tasks/deploy-project.yml
        input_mapping: {src: prometheus-aws-configuration-beta}
        params:
          PROJECT: alertmanager-production
          DEPLOYER_ARN: arn:aws:iam::455214962221:role/autom8-deployer
          GPG_PRIVATE_KEY: ((gpg_private_key))
      - in_parallel:
        - task: smoke-test-alertmanager
          attempts: 4
          timeout: 2m
          file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
          params:
            URL: https://alerts.monitoring.gds-reliability.engineering/-/healthy
        - task: smoke-test-alertmanager-eu-west-1a
          attempts: 4
          timeout: 2m
          file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
          params:
            URL: https://alerts-eu-west-1a.monitoring.gds-reliability.engineering/-/healthy
        - task: smoke-test-alertmanager-eu-west-1b
          attempts: 4
          timeout: 2m
          file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
          params:
            URL: https://alerts-eu-west-1b.monitoring.gds-reliability.engineering/-/healthy
        - task: smoke-test-alertmanager-eu-west-1c
          attempts: 4
          timeout: 2m
          file: prometheus-aws-configuration-beta/ci/tasks/http-ping.yml
          params:
            URL: https://alerts-eu-west-1c.monitoring.gds-reliability.engineering/-/healthy

  - name: run-service-broker-tests
    plan:
      - get: cf-app-discovery
        trigger: true
      - task: run-tests
        timeout: 15m
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.6.6
          inputs:
            - name: cf-app-discovery
              path: repo
          run:
            path: sh
            dir: repo
            args:
            - -c
            - |
              apt-get update
              gem install bundler -v 2.0.1
              bundle install --without development
              bundle exec rake
  - name: deploy-service-broker-ireland-staging
    plan:
      - get: cf-app-discovery
        trigger: true
        passed: [ run-service-broker-tests ]
      - put: service-broker-ireland-staging
        params:
          manifest: cf-app-discovery/manifest-ireland-staging.yml
          show_app_log: true
  - name: deploy-service-broker-ireland-production
    plan:
      - get: cf-app-discovery
        trigger: true
        passed: [ deploy-service-broker-ireland-staging ]
      - put: service-broker-ireland-production
        params:
          manifest: cf-app-discovery/manifest-ireland-production.yml
          show_app_log: true
  - name: deploy-service-broker-london-production
    plan:
      - get: cf-app-discovery
        trigger: true
        passed: [ deploy-service-broker-ireland-staging ]
      - put: service-broker-london-production
        params:
          manifest: cf-app-discovery/manifest-london-production.yml
          show_app_log: true
